# Generated by Django 6.0.2 on 2026-04-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='highlight_rects',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
