# Generated by Django 6.0.2 on 2026-04-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_note_highlight_rects'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(default='#ffe244', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
