# Generated by Django 6.0.2 on 2026-04-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0004_note_color_note_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
