# Generated by Django 6.0.2 on 2026-02-17 16:57

import apps.accounts.models
from django.db import migrations, models


def _backfill_numeric_tokens(apps, schema_editor):
    EmailVerificationToken = apps.get_model('accounts', 'EmailVerificationToken')
    used_tokens = set(
        EmailVerificationToken.objects.values_list('token', flat=True)
    )

    for row in EmailVerificationToken.objects.all().order_by('id'):
        if len(row.token) == 6 and row.token.isdigit():
            continue

        used_tokens.discard(row.token)

        for _ in range(50):
            import secrets
            candidate = f"{secrets.randbelow(1_000_000):06d}"
            if candidate not in used_tokens:
                row.token = candidate
                row.save(update_fields=['token'])
                used_tokens.add(candidate)
                break
        else:
            raise RuntimeError("Could not generate unique 6-digit verification token")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verified_user_email_verified_at_and_more'),
    ]

    operations = [
        migrations.RunPython(_backfill_numeric_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.CharField(default=apps.accounts.models.generate_email_verification_code, max_length=6, unique=True),
        ),
    ]
