# Generated by Django 6.0.2 on 2026-03-10 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGamification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('books_finished', models.PositiveIntegerField(default=0)),
                ('total_pages_read', models.PositiveIntegerField(default=0)),
                ('total_time_hours', models.FloatField(default=0.0)),
                ('last_read_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('first_book', 'First Book Finished'), ('streak_7', '7-Day Streak'), ('streak_30', '30-Day Streak'), ('pages_100', '100 Pages Read'), ('pages_1000', '1,000 Pages Read'), ('xp_500', '500 XP Earned'), ('xp_5000', '5,000 XP Earned'), ('night_owl', 'Night Owl — read after 10PM'), ('early_bird', 'Early Bird — read before 7AM'), ('speed_reader', 'Speed Reader — 50 pages in one session')], max_length=30)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge_type')},
            },
        ),
    ]
