# Generated by Django 6.0.2 on 2026-02-19 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('isbn_10', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('isbn_13', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('cover_url', models.URLField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('publisher', models.CharField(blank=True, default='', max_length=300)),
                ('published_date', models.CharField(blank=True, default='', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('google_books_id', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_books', to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(blank=True, related_name='books', to='books.genre')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
