# Generated by Django 6.0.2 on 2026-04-06 06:37

from django.core.validators import FileExtensionValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_file_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to='books/pdfs/',
                validators=[FileExtensionValidator(['pdf'])],
            ),
        ),
    ]
