# Generated by Django 6.0.2 on 2026-04-06 06:38

from django.db import migrations, connection


def alter_file_column(apps, schema_editor):
    """Alter the file column to VARCHAR(500) for all databases."""
    db_vendor = connection.vendor
    if db_vendor == 'postgresql':
        schema_editor.execute("ALTER TABLE books_book ALTER COLUMN file TYPE VARCHAR(500);")
    elif db_vendor == 'sqlite':
        # SQLite doesn't support ALTER COLUMN TYPE directly
        # The table recreation in migration 0003 should have handled this
        pass
    elif db_vendor == 'mysql':
        schema_editor.execute("ALTER TABLE books_book MODIFY COLUMN file VARCHAR(500);")


def reverse_alter_file_column(apps, schema_editor):
    """Reverse the alteration."""
    db_vendor = connection.vendor
    if db_vendor == 'postgresql':
        schema_editor.execute("ALTER TABLE books_book ALTER COLUMN file TYPE VARCHAR(100);")
    elif db_vendor == 'sqlite':
        pass
    elif db_vendor == 'mysql':
        schema_editor.execute("ALTER TABLE books_book MODIFY COLUMN file VARCHAR(100);")


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_force_alter_file_field'),
    ]

    operations = [
        migrations.RunPython(
            alter_file_column,
            reverse_code=reverse_alter_file_column,
        ),
    ]
