# Generated by Django 6.0.2 on 2026-03-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='timezone',
            field=models.CharField(default='Africa/Kampala', max_length=50),
        ),
    ]
