# Generated by Django 6.0.2 on 2026-03-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationpreference_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='last_reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
